done
ulianabarnas/nodejs-homework-rest-api pull request #1
Opened 2023-01-14 23:43 UTC by ulianabarnas

Вітаю! Перевірте, будь ласка.

2023-01-15 07:27 UTC, KhYulian commented on app.js
> +  }
Можна скоротити. Використайте ||

2023-01-15 07:28 UTC, KhYulian commented on helpers/index.js
> +}
Використовуйте класи https://javascript.info/custom-errors

2023-01-15 07:28 UTC, KhYulian commented on middlewares/index.js
> +    }
Це зайве. Схема Joi перевірить поля, їх наявність, та відповідність схемі

2023-01-15 07:29 UTC, KhYulian commented on models/contacts.js
> +const listContacts = async () => {
getContacts

2023-01-15 07:30 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-17 11:01 UTC, ulianabarnas commented on models/contacts.js
> +const listContacts = async () => {
Ніяк не можу зрозуміти, що потрібно виправити?

2023-01-17 16:21 UTC, KhYulian approved these changes
Чудова робота :heart:

2023-01-17 16:22 UTC, merged